root = "."
tmp_dir = "tmp"

[build]
  entrypoint = ["back-end/cmd/main.go"]
  cmd = "go build -o ./tmp/main ./back-end/cmd/main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", ".git", "vendor", "node_modules"]
  include_dir = ["backend", "frontend"]
  include_ext = ["go", "html", "css", "js"]
  send_interrupt = true

[log]
  time = true

[misc]
  clean_on_exit = true
